"""
AI Coding Teammate - Response Utilities
=======================================

Provides consistent response dictionaries for the AI layer.

Used by:
- CodeAnalyzer
- CodeCorrector
- CodeExplainer
- ErrorDetector
- VisualAnalyzer
- ProjectAnalyzer
- AIEngine

The helpers accept **extra so additional fields can be added
without breaking existing callers.
"""


# ============================================================
# ANALYSIS RESPONSE
# ============================================================

def create_analysis_response(
    summary: str = "",
    success: bool = True,
    errors=None,
    warnings=None,
    suggestions=None,
    **extra,
):
    """
    Create a normalized code-analysis response.

    Parameters
    ----------
    summary:
        Human-readable analysis summary.

    success:
        Indicates whether the analysis succeeded.

    errors:
        Detected errors.

    warnings:
        Detected warnings.

    suggestions:
        Suggested improvements.

    **extra:
        Additional fields such as:
        - explanation
        - original_code
        - corrected_code
        - highlighted_lines
        - model
        - model_name
        - processing_time
    """

    errors = errors or []
    warnings = warnings or []
    suggestions = suggestions or []

    response = {
        "success": bool(success),
        "type": "analysis",

        # Keep both names for compatibility.
        "content": summary or "",
        "summary": summary or "",

        "errors": errors,
        "warnings": warnings,
        "suggestions": suggestions,

        "error_count": len(errors),
        "warning_count": len(warnings),
    }

    response.update(extra)

    return response


# ============================================================
# CORRECTION RESPONSE
# ============================================================

def create_correction_response(
    original_code: str = "",
    corrected_code: str = "",
    explanation: str = "",
    success: bool = True,
    **extra,
):
    """
    Create a normalized code-correction response.

    Parameters
    ----------
    original_code:
        Original source code supplied by the developer.

    corrected_code:
        Corrected source code generated by the AI.

    explanation:
        Explanation of the changes.

    success:
        Indicates whether correction succeeded.

    **extra:
        Additional response fields.
    """

    response = {
        "success": bool(success),
        "type": "correction",

        "original_code": (
            original_code
            if original_code is not None
            else ""
        ),

        "corrected_code": (
            corrected_code
            if corrected_code is not None
            else ""
        ),

        "explanation": explanation or "",
    }

    response.update(extra)

    return response


# ============================================================
# GENERIC AI RESPONSE
# ============================================================

def create_response(
    response_type: str = "",
    message: str = "",
    success: bool = True,
    **extra,
):
    """
    Create a generic AI response.

    Useful for:
    - explanations
    - chat responses
    - project analysis
    - AI status messages
    """

    response = {
        "success": bool(success),
        "type": response_type or "response",

        # Keep message as the primary field.
        "message": message or "",

        # Also expose content because several AI components
        # already use the "content" convention.
        "content": message or "",
    }

    response.update(extra)

    return response


# ============================================================
# VISUAL ANALYSIS RESPONSE
# ============================================================

def create_visual_response(
    message: str = "",
    observations=None,
    errors=None,
    suggestions=None,
    success: bool = True,
    **extra,
):
    """
    Create a normalized visual-analysis response.

    Used for:
    - screenshots
    - screen sharing
    - camera frames
    - uploaded images
    - visual debugging
    """

    observations = observations or []
    errors = errors or []
    suggestions = suggestions or []

    response = {
        "success": bool(success),
        "type": "visual_analysis",

        "message": message or "",
        "content": message or "",

        "observations": observations,
        "errors": errors,
        "suggestions": suggestions,

        "error_count": len(errors),
    }

    response.update(extra)

    return response